### ISSUE TITLE
Trident causing crash with Iris + EMF

### ISSUE THREAD

**Issue by snatella** [FabianMPunkt/Nautilus3D#12]
### Game Version

fabric-loader-0.15.3 (1.20.2)

### List all installed mods

3d Skin Layers 1.5.6-mc1.20.2
Advanced UI Scaling 1.2.1-1.20.2
Entity Model Features 1.2
Entity Texture Features 5.0
Fabric API 0.91.2+1.20.2
Iris 1.6.14
Lithium 1.4.5
Mod Menu 8.0.1
Sodium 0.5.5

### List of all loaded packs

Nautilus3D-V1.9.1
(Shader) BSL v8.2.07.1

### Describe your issue

Using the Trident with the resource pack loaded causes an immediate game crash and stack trace.

Now probably EMF/Iris should not crash, but it's only this resource packs Trident (I've been trying out a few).

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1921.method_23033()" because "<parameter1>" is null
	at net.coderbot.batchedentityrendering.impl.RenderTypeUtil.isTriangleStripDrawMode(RenderTypeUtil.java:8)
	at net.coderbot.batchedentityrendering.impl.SegmentedBufferBuilder.getBuffer(SegmentedBufferBuilder.java:47)
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.getBuffer(FullyBufferedMultiBufferSource.java:93)
	at traben.entity_texture_features.features.ETFRenderContext.processVertexConsumer(ETFRenderContext.java:107)
	at traben.entity_model_features.models.EMFModelPart.renderWithTextureOverride(EMFModelPart.java:65)
	at traben.entity_model_features.models.EMFModelPartCustom.method_22699(EMFModelPartCustom.java:129)
	at traben.entity_model_features.models.EMFModelPart.renderLikeVanilla(EMFModelPart.java:81)
	at traben.entity_model_features.models.EMFModelPart.renderLikeETF(EMFModelPart.java:94)
	at traben.entity_model_features.models.EMFModelPart.renderWithTextureOverride(EMFModelPart.java:47)
	at traben.entity_model_features.models.EMFModelPartWithState.method_22699(EMFModelPartWithState.java:46)
	at traben.entity_model_features.models.EMFModelPartVanilla.method_22699(EMFModelPartVanilla.java:62)
	at net.minecraft.class_613.method_2828(class_613.java:59)
	at net.minecraft.class_756.method_3166(class_756.java:157)
	at net.minecraft.class_918.method_23179(class_918.java:126)
	at net.minecraft.class_918.method_23177(class_918.java:271)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_759.method_3228(class_759.java:620)
	at net.minecraft.class_759.method_22976(class_759.java:396)
	at net.minecraft.class_757.redirect$zpn000$iris$disableVanillaHandRendering(class_757.java:3147)
	at net.minecraft.class_757.method_3172(class_757.java:815)
	at net.minecraft.class_757.method_3188(class_757.java:1140)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by FabianMPunkt** [comment]
Hey thanks for reporting.
Entity models really are something else.. I've noticed a few issues aswell.
Please first try updating your installation of fabric loader and all your mods to the newest version.

**Comment by snatella** [comment]
I reinstalled this about 2 days ago, and there's already some big updates, wow!

After updating 
- 3d Skin Layers 1.6.2
- Entity Texture Features 5.2.1
- Entity Model Features 1.2.3
- Fabric API 0.91.4+1.20.2

The trident no longer causes any crashes, it is just invisible.

**Comment by FabianMPunkt** [comment]
It looks like EMF shows an invisible model, when it's texture is in a different directory than the default one. Fix will be in the next Nautilus update.
In the mean time you can download the current trident file from GitHub, and move the Trident texture from _minecraft/textures/custom_textures_ to _minecraft/textures/entity_
(28bf497)

**Comment by snatella** [comment]
Awesome! I can now see the Trident. However...

Now, the closest prong of the trident is partially invisible. The tip is there, but the "block" back from it is not.

![image](https://github.com/FabianMPunkt/Nautilus3D/assets/13870273/d8f3c223-5f70-423a-88ff-f464f0c1d7fa)

**Comment by FabianMPunkt** [comment]
Oh wat this is really strange..
Are you sure that the new trident is in minecraft/optifine/cem
and the texture is in _minecraft/textures/entity_

I'd be best if you just download the entire GitHub repo and move the texture pack to the minecraft folder.

**Comment by snatella** [comment]
Sorry @FabianMPunkt I totally forgot to report back here after doing just that - it shows up correctly doing that, so not sure what I did wrong with moving/editing the files originally but yes this is fixed by your commit.
